### ISSUE TITLE
move to gopacket?

### ISSUE THREAD

**Issue by vtolstov** [mdlayher/geneve#1]
Hi i see you have many parsing libs , do you thinks to move it to gopacket?

**Comment by mdlayher** [comment]
Looks like it should be pretty trivial to add Geneve to gopacket.  I can look into it for sure.

**Comment by vtolstov** [comment]
thanks! Also  this is very useful for vxlan =).
Sorry for offtopic, what you use in DO as network layer (i'm work on Russian hosting), do you use openvswitch or use plain routing (we use ospf and L3 routing)
